services:
  postgres:
    image: postgres:15
    container_name: feature_store_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: featurestore
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: feature_store_redis
    ports:
      - "6379:6379"
      